version: "3.9"

x-restart-policy: &restart-policy
    restart: always

services:
    nginx:
        <<: *restart-policy
        image: nginx:1.19
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
        depends_on:
            - php

    php:
        <<: *restart-policy
        build:
            context: ./docker/images/php-fpm
        user: "${UID}"
        volumes:
            - ./:/var/www/app
        depends_on:
            - redis
            - mysql
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.hnn-laravel-schedule.schedule: "0 * * * * *"
            ofelia.job-exec.hnn-laravel-schedule.command: "php artisan schedule:run --verbose --no-interaction"

    redis:
        <<: *restart-policy
        image: redis:6.2
        volumes:
            - redis-data:/data

    ofelia:
        <<: *restart-policy
        image: mcuadros/ofelia:latest
        command: daemon --docker
        depends_on:
            - php
        volumes:
            - ${DOCKER_SOCKET}:/var/run/docker.sock:ro

    mysql:
        <<: *restart-policy
        image: mysql:8
        env_file: ./docker/mysql/.env
        cap_add:
            - SYS_NICE
        ports:
            - "${MYSQL_PORT}:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        tmpfs:
            - /tmp

    pma:
        <<: *restart-policy
        image: phpmyadmin:5.1
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - PMA_PORT=${MYSQL_PORT}
        depends_on:
            - mysql
        ports:
            - "${PMA_PORT}:80"

    mailhog:
        <<: *restart-policy
        image: mailhog/mailhog:v1.0.1
        ports:
            - "${MAILHOG_PORT}:8025"

volumes:
    mysql-data:
    redis-data:
